defaults:
  - hrnet_base_config.yaml


LAYER1:
  TRANS_CHANNELS: [18, 36]

STAGE2:
  NUM_MODULES: 1
  NUM_BRANCHES: 2
  NUM_BLOCKS: [4]
  INPUT_CHANNELS: [18, 36]
  OUTPUT_CHANNELS: [18, 36, 72]
  BLOCK: 'BASIC'
  FUSE_METHOD: 'SUM'

STAGE3:
  NUM_MODULES: 4
  NUM_BRANCHES: 3
  NUM_BLOCKS: [4]
  INPUT_CHANNELS: [18, 36, 72]
  OUTPUT_CHANNELS: [18, 36, 72, 144]
  BLOCK: 'BASIC'
  FUSE_METHOD: 'SUM'

STAGE4:
  NUM_MODULES: 3
  NUM_BRANCHES: 4
  NUM_BLOCKS: [4]
  INPUT_CHANNELS: [18, 36, 72, 144]
  OUTPUT_CHANNELS: [18, 36, 72, 144]
  BLOCK: 'BASIC'
  FUSE_METHOD: 'SUM'
  MULTI_SCALE_OUTPUT: False

model_urls: